### ISSUE TITLE
Resource limit breaks retdec

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/decompiler-explorer#12]
Setting the hard limit less than INFINITY causes it to crash. Only on the deploy server though, this did not happen on my local install.

```
>>> args.mem_limit_soft=10000000000
>>> args.mem_limit_hard=10000000000
>>> decompile_source(args, conts)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 9, in decompile_source
__main__.DecompileError: b'Traceback (most recent call last):\n  File "decompile_retdec.py", line 58, in <module>\n    main()\n  File "decompile_retdec.py", line 23, in main\n    subprocess.check_call([RETDEC_DECOMPILER, \'--output\', outfile.name, \'--cleanup\', \'--silent\', infile.name], stdout=subprocess.PIPE, stderr=subprocess.PIPE)\n  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call\n    raise CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command \'[PosixPath(\'/home/decompiler_user/retdec/bin/retdec-decompiler\'), \'--output\', \'/tmp/tmpgp113qgs/tmp18f8xilr\', \'--cleanup\', \'--silent\', \'/tmp/tmpgp113qgs/tmpqfw3g882\']\' died with <Signals.SIGABRT: 6>.\n'

>>> args.mem_limit_soft=100000000000
>>> args.mem_limit_hard=100000000000
>>> decompile_source(args, conts)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 9, in decompile_source
__main__.DecompileError: b'Traceback (most recent call last):\n  File "decompile_retdec.py", line 58, in <module>\n    main()\n  File "decompile_retdec.py", line 23, in main\n    subprocess.check_call([RETDEC_DECOMPILER, \'--output\', outfile.name, \'--cleanup\', \'--silent\', infile.name], stdout=subprocess.PIPE, stderr=subprocess.PIPE)\n  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call\n    raise CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command \'[PosixPath(\'/home/decompiler_user/retdec/bin/retdec-decompiler\'), \'--output\', \'/tmp/tmpnd1o63o3/tmp94lqqgqz\', \'--cleanup\', \'--silent\', \'/tmp/tmpnd1o63o3/tmp_fhab1h3\']\' died with <Signals.SIGABRT: 6>.\n'

>>> args.mem_limit_soft=100000000000
>>> args.mem_limit_hard=resource.RLIM_INFINITY
>>> decompile_source(args, conts)
b'<pre>//\n// This file was generated by the Retargetable Decompiler\n// Website: https://retdec.com\n//\n\n#include <stdint.h>\n#include <stdio.h>\n\n// ------------------- Function Prototypes --------------------\n\nint64_t __do_global_dtors_aux(void);\nint64_t __libc_csu_fini(void);\nint64_t __libc_csu_init(void);\nint64_t _fini(void);\nint64_t _init(void);\nint64_t _start(void);\nint64_t deregister_tm_clones(void);\nint64_t frame_dummy(void);\nint64_t function_1003(void);\nint64_t function_1040(void);\nvoid function_1043(int64_t * d);\nint64_t function_1050(void);\nint32_t function_1053(char * format, ...);\nint64_t function_1103(void);\nint64_t function_1143(void);\n...'

>>> args.mem_limit_soft=resource.RLIM_INFINITY
>>> args.mem_limit_hard=resource.RLIM_INFINITY
>>> decompile_source(args, conts)
b'<pre>//\n// This file was generated by the Retargetable Decompiler\n// Website: https://retdec.com\n//\n\n#include <stdint.h>\n#include <stdio.h>\n\n// ------------------- Function Prototypes --------------------\n\nint64_t __do_global_dtors_aux(void);\nint64_t __libc_csu_fini(void);\nint64_t __libc_csu_init(void);\nint64_t _fini(void);\nint64_t _init(void);\nint64_t _start(void);\nint64_t deregister_tm_clones(void);\nint64_t frame_dummy(void);\nint64_t function_1003(void);\nint64_t function_1040(void);\nvoid function_1043(int64_t * d);\nint64_t function_1050(void);\nint32_t function_1053(char * format, ...);\nint64_t function_1103(void);\nint64_t function_1143(void);\n...'
```

**Comment by CouleeApps** [comment]
Addressed by 7c44ccac0731c2bfee2f046c8fc1427336080521
